### ISSUE TITLE
What about cli version?

### ISSUE THREAD

**Issue by a-x-** [bem-sdk/bem-naming#117]

**Comment by a-x-** [comment]
my quick dirty reference implementation: https://github.com/a-x-/bem-naming-cli/blob/master/bem-naming

**Comment by blond** [comment]
Hi!

I think than with cli we want get info about files. For example, you can use [bem-find](https://github.com/bem-contrib/bem-tools-find).

Can you tell me what's the point of this?

Maybe we need to make another plugin for `bem-tools`?

**Comment by a-x-** [comment]
i want get struclural parts of bem names and check them, not to find files.

```bash
bem-naming bem_dfsf isBlockMod        # (stdout: "True")
bem-naming bem__fdsfs_dfsf isBlockMod # (stdout: "\n")
bem-naming bem__fdsfs_dfsf isElemMod  # True
bem-naming foo__bar_baz .block        # foo
bem-naming foo__bar_baz .elem         # bar
```

**Comment by blond** [comment]
I still don't understand why. 

@a-x- explain where it is to be used? In other tools or for users to to test `bem-naming`?

But if do, then I would prefer this CLI:

```
Usage
  $ bem-entity-part <command> <bem-entity-part>
    
Commands
  type   Returns type of BEM entity part
  block  Returns block name of BEM entity part
  elem   Returns elem name of BEM entity part
  mod    Returns mod of BEM entity part
  
Options
  --naming  Include a rainbow

Examples
  $ bem-entity-part type button_disabled
  blockMod

  $ bem-entity-part block button__text
  button

  $ bem-entity-part block button--checked --naming=two-dashes
  blockMod
```

Now we think about [move](https://github.com/bem-sdk/bem-naming/issues/98) part API from `bem-naming` to [bem-entity](https://github.com/bem-sdk/bem-entity) package. In `bem-naming` must remain `parse` and `stringify` methods.

@a-x- your example more suited to `bem-entity-part`.

**Comment by a-x-** [comment]
sometimes i need to fast write bash one-liners working with bem world.

> bem-entity-part

It's cool and acceptable for me.
But name `bem-entity-part` is not clear as i see. More comprehensible for me would be `bem-naming` cli api.

**Comment by a-x-** [comment]
add reference to `bem-entity-part` cli on bem-naming readme please, as far as it'll be ready

**Comment by Yeti-or** [comment]
I think that `tenorok` is more suitable name

**Comment by blond** [comment]
@a-x- thanks for the explanation )

> add reference to bem-entity-part cli on bem-naming readme please, as far as it'll be ready

sure

**Comment by blond** [comment]
Still bothers me that `bem-sdk` packages will have cli dependencies.

We can create `bem-entity-part-cli` package or create `bem-tools-entity-part` plugin, which will be provided `entity-part` command. 

```
$ bem entity-part type button_disabled
```

**Comment by blond** [comment]
I publish [@bem/entity-name](https://github.com/bem-sdk/bem-entity-name) `v1.0.0`.

@a-x- You can use it to create `bem-tools-entity-name` plugin.
